const test = require('node:test');
const assert = require('node:assert/strict');
const { generateMarkdown } = require('../src/markdown-generator');

const basePayload = {
  winget: ['Git.Git', 'Microsoft.VSCode'],
  npm: ['typescript', 'nodemon'],
  pip: [{ name: 'requests', version: '2.31.0' }],
  manual_apps: [{ name: 'SomeApp', version: '1.0.0', publisher: 'SomePublisher' }]
};

test('full backup renders all four sections and summary counts', () => {
  const md = generateMarkdown(basePayload, {
    versions: { winget: { 'Git.Git': '2.43.0' }, npm: { typescript: '5.3.2' } }
  });
  assert.match(md, /# Windows Development Setup Backup/);
  assert.match(md, /## Summary/);
  assert.match(md, /## Winget Apps \(2 packages\)/);
  assert.match(md, /## NPM Global Packages \(2 packages\)/);
  assert.match(md, /## PIP Packages \(1 packages\)/);
  assert.match(md, /## Manual Apps/);
  assert.match(md, /\*Generated by win-sync CLI tool\*/);
});

test('includeManualApps false omits manual section and shows 0', () => {
  const md = generateMarkdown(basePayload, { includeManualApps: false });
  assert.doesNotMatch(md, /## Manual Apps/);
  assert.match(md, /\| Manual Apps \| 0 \| Excluded from backup \|/);
});

test('winget and npm versions come from versions map with em-dash fallback', () => {
  const md = generateMarkdown(basePayload, {
    versions: {
      winget: { 'Git.Git': '2.43.0' },
      npm: { typescript: '5.3.2' }
    }
  });
  assert.match(md, /\| Git\.Git \| 2\.43\.0 \|/);
  assert.match(md, /\| Microsoft\.VSCode \| — \|/);
  assert.match(md, /\| typescript \| 5\.3\.2 \|/);
  assert.match(md, /\| nodemon \| — \|/);
});

test('pip versions come from payload', () => {
  const md = generateMarkdown(basePayload, {});
  assert.match(md, /\| requests \| 2\.31\.0 \|/);
});

test('a pipe in a package name is escaped and does not break the table', () => {
  const payload = {
    winget: ['Weird|Name'],
    npm: [],
    pip: [],
    manual_apps: []
  };
  const md = generateMarkdown(payload, {});
  assert.match(md, /\| Weird\\\|Name \| — \|/);
});

test('empty categories still render summary row with 0 and a placeholder line', () => {
  const md = generateMarkdown({ winget: [], npm: [], pip: [], manual_apps: [] }, {});
  assert.match(md, /\| Winget Apps \| 0 \| ✅ Auto-restorable \|/);
  assert.match(md, /## Winget Apps \(0 packages\)/);
  assert.match(md, /No packages found\./);
});

test('no ANSI escape codes in markdown output', () => {
  const md = generateMarkdown(basePayload, {});
  assert.doesNotMatch(md, /\u001b\[[0-9;]*m/);
});